spring:
  profiles:
    active: @spring.profiles.active@
  security:
    user:
      password: 'admin'
      name: 'admin'

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
