spring:
  cloud:
    nacos:
      server-addr: 47.107.103.108:9020
  application:
    name: spring-boot-admin-client
  security:
    user:
      name: 'admin'
      password: 'admin@13579'

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator

server:
  port: 8001
